import './globals.css'
import type { Metadata } from 'next'
import { Libre_Baskerville, Inter } from 'next/font/google';
import localFont from 'next/font/local'
import Header from './components/header'
import Footer from './components/footer'
import {Navbar, NavbarBrand, NavbarContent, NavbarItem, Link, Button} from "@nextui-org/react";


const libreBaskerville = Libre_Baskerville({
  weight: ['400', '700'], 
  subsets: ['latin'],
});

const inter = Inter({
  subsets: ['latin']
})

const gistesy = localFont({src: '/ui/Gistesy.ttf'})

export const metadata: Metadata = {
  title: 'Bay6 Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={libreBaskerville.className}>
        <Header/> 
        {children}
        <Footer/>
        </body>
    </html>
  )
}
